name: Ruku
description: The backend for the Sujud app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  amplify_flutter: ^0.6.0
  amplify_datastore: ^0.6.0

flutter:
  uses-material-design: true
