# ------------------------------------------------------------------------------------- MODELS

type Announcement
  @model(
    mutations: { 
      create: "createAnnouncement"
      update: null
      delete: "deleteAnnouncement"
    }
    subscriptions: {
      onCreate: ["onCreateAnnouncement"]
      onUpdate: [null]
      onDelete: ["onDeleteAnnouncement"]
    }
  )
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  type: AnnouncementType!
  content: AWSJSON!
  images: [String]
  bookmarks: [Bookmark]! @hasMany(indexName: "byAnnouncement", fields: ["id"])
  likes: [Like]! @hasMany(indexName: "byAnnouncement", fields: ["id"])
  comments: [Comment]! @hasMany(indexName: "byAnnouncement", fields: ["id"])
  creatorID: ID! @index(name: "byCreator")
  creator: User! @belongsTo(fields: ["creatorID"])
  mosqueID: ID! @index(name: "byMosque")
  mosque: Mosque! @belongsTo(fields: ["mosqueID"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
}

type Bookmark
  @model(
    queries: null
    mutations: { 
      create: "createBookmark",
      update: null,
      delete: "deleteBookmark",
    }
    subscriptions: null
  )
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  announcementID: ID! @index(name: "byAnnouncement")
  announcement: Announcement! @belongsTo(fields: ["announcementID"])
  creatorID: ID! @index(name: "byCreator")
  creator: User! @belongsTo(fields: ["creatorID"])
  mosqueID: ID! @index(name: "byMosque")
  mosque: Mosque! @belongsTo(fields: ["mosqueID"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
}

type Comment
  @model(
    queries: null
    mutations: {
      create: "createComment",
      update: null,
      delete: "deleteComment",
    }
    subscriptions: null
  )
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  text: String!
  parentCommentID: ID @index(name: "byParentComment")
  parentComment: Comment @belongsTo(fields: ["parentCommentID"])
  subComments: [Comment]! @hasMany(indexName: "byParentComment", fields: ["id"])
  announcementID: ID! @index(name: "byAnnouncement")
  announcement: Announcement! @belongsTo(fields: ["announcementID"])
  creatorID: ID! @index(name: "byCreator")
  creator: User! @belongsTo(fields: ["creatorID"])
  mosqueID: ID! @index(name: "byMosque")
  mosque: Mosque! @belongsTo(fields: ["mosqueID"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
}

type Donation
  @model(
    queries: null
    mutations: { 
      create: "createDonation",
      update: null,
      delete: "deleteDonation",
    }
    subscriptions: {
      onCreate: ["onCreateDonation"]
      onUpdate: [null]
      onDelete: ["onDeleteDonation"]
    }
  )
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  amount: Float!
  currency: String!
  isAnonymous: Boolean!
  donorID: ID! @index(name: "byDonor")
  donor: User! @belongsTo(fields: ["donorID"])
  fundraisingCampaignID: ID! @index(name: "byFundraisingCampaign")
  fundraisingCampaign: FundraisingCampaign @belongsTo(fields: ["fundraisingCampaignID"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
}

type FundraisingCampaign
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "owners"}
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  title: String!
  description: String
  featureImage: String
  type: FundraisingCampaignType!
  currentAmount: Float!
  goal: Float!
  goalDate: AWSDateTime!
  currency: String!
  creatorID: ID! @index(name: "byCreator")
  creator: User! @belongsTo(fields: ["creatorID"])
  mosqueID: ID! @index(name: "byMosque")
  mosque: Mosque! @belongsTo(fields: ["mosqueID"])
  donations: [Donation]! @hasMany(indexName: "byFundraisingCampaign", fields: ["id"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owners: [String] @auth(rules: [{ allow: owner }])
}

type Like
  @model(
    queries: null
    mutations: { 
      create: "createLike",
      update: null,
      delete: "deleteLike",
    }
    subscriptions: null
  )
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  announcementID: ID! @index(name: "byAnnouncement")
  announcement: Announcement! @belongsTo(fields: ["announcementID"])
  creatorID: ID! @index(name: "byCreator")
  creator: User! @belongsTo(fields: ["creatorID"])
  mosqueID: ID! @index(name: "byMosque")
  mosque: Mosque! @belongsTo(fields: ["mosqueID"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
}

type PrayerTime
  @model(
    queries: null
  )
  @auth(
    rules: [
      { allow: owner, ownerField: "owners"}
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  )
  {
  id: ID!
  fajr: FardPrayer!
  dhuhr: FardPrayer!
  asr: FardPrayer!
  maghrib: FardPrayer!
  isha: FardPrayer!
  jummah: [FardPrayer]!
  taraweeh: SunnahPrayer
  eid: [FardPrayer]
  startDate: AWSDateTime!
  timeZone: String!
  createdByUserID: ID! @index(name: "byCreatedByUser")
  createdByUser: User! @belongsTo(fields: ["createdByUserID"])
  updatedByUserID: ID! @index(name: "byUpdatedByUser")
  updatedByUser: User! @belongsTo(fields: ["updatedByUserID"])
  mosqueID: ID! @index(name: "byMosque")
  mosque: Mosque! @belongsTo(fields: ["mosqueID"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owners: [String] @auth(rules: [{ allow: owner }])
}

type Mosque
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "owners" }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  name: String!
  description: String!
  images: [String!]!
  address: String!
  latitude: Float!
  longitude: Float!
  hours: Hours
  phone: AWSPhone
  email: AWSEmail
  website: String
  socialMedia: SocialMedia
  isVerified: Boolean @default(value: "false") @auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  )
  creatorID: ID! @index(name: "byCreator") @auth(
    rules: [
      { allow: owner, ownerField: "owners", operations: [create, read]}
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  )
  creator: User! @belongsTo(fields: ["creatorID"]) @auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  )
  organizationID: ID @index(name: "byOrganization")
  organization: Organization @belongsTo(fields: ["organizationID"])
  followers: [User]! @manyToMany(relationName: "MosqueFollower")
  announcements: [Announcement]! @hasMany(indexName: "byMosque", fields: ["id"])
  fundraisingCampaigns: [FundraisingCampaign]! @hasMany(indexName: "byMosque", fields: ["id"])
  prayerTimes: [PrayerTime]! @hasMany(indexName: "byMosque", fields: ["id"])
  bookmarks: [Bookmark]! @hasMany(indexName: "byMosque", fields: ["id"])
  likes: [Like]! @hasMany(indexName: "byMosque", fields: ["id"])
  comments: [Comment]! @hasMany(indexName: "byMosque", fields: ["id"])
  createdAt: AWSDateTime! @auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  )
  updatedAt: AWSDateTime!
  owners: [String] @auth(rules: [{ allow: owner }])
}

type Organization
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "owners" }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  name: String!
  description: String
  domain: String
  logo: String
  phone: AWSPhone
  email: AWSEmail
  website: String
  isVerified: Boolean! @default(value: "false") @auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  )
  creatorID: ID! @index(name: "byCreator") @auth(
    rules: [
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  )
  creator: User! @belongsTo(fields: ["creatorID"])
  members: [OrganizationMember]! @hasMany(indexName: "byOrganization", fields: ["id"])
  mosques: [Mosque]! @hasMany(indexName: "byOrganization", fields: ["id"])
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  owners: [String] @auth(rules: [{ allow: owner }])
}

type OrganizationMember
  @model(
    queries: null
    mutations: { 
      create: "createOrganizationMember",
      update: null,
      delete: "deleteOrganizationMember",
    }
    subscriptions: null
  )
  @auth(
    rules: [
      { allow: owner, ownerField: "owners" }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  role: MemberRole!
  organizationID: ID! @index(name: "byOrganization")
  organization: Organization! @belongsTo(fields: ["organizationID"])
  memberID: ID! @index(name: "byMember")
  member: User! @belongsTo(fields: ["memberID"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owners: [String] @auth(rules: [{ allow: owner }])
}

type User
	@model(
    queries: {
      get: "getUser",
      list: null,
    }
		mutations: {
      create: null,
      update: "updateUser",
      delete: null,
    }
    subscriptions: null
	)
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read] }
      { allow: public, operations: [read] }
    ]
  ) {
  id: ID!
  selfie: String
  firstName: String!
  lastName: String!
  email: AWSEmail!
  phone: AWSPhone
  type: UserType!
  status: UserStatus!
  stripeCustomerId: String
  isOnline: Boolean
  bookmarks: [Bookmark]! @hasMany(indexName: "byCreator", fields: ["id"])
  comments: [Comment]! @hasMany(indexName: "byCreator", fields: ["id"])
  createdAnnouncements: [Announcement]! @hasMany(indexName: "byCreator", fields: ["id"])
  createdFundraisingCampaigns: [FundraisingCampaign]! @hasMany(indexName: "byCreator", fields: ["id"])
  createdPrayerTimes: [PrayerTime]! @hasMany(indexName: "byCreatedByUser", fields: ["id"])
  createdOrganizations: [Organization]! @hasMany(indexName: "byCreator", fields: ["id"])
  createdMosques: [Mosque]! @hasMany(indexName: "byCreator", fields: ["id"])
  donations: [Donation]! @hasMany(indexName: "byDonor", fields: ["id"])
  mosques: [Mosque]! @manyToMany(relationName: "MosqueFollower")
  organizations: [OrganizationMember]! @hasMany(indexName: "byMember", fields: ["id"])
  likes: [Like]! @hasMany(indexName: "byCreator", fields: ["id"])
  updatedPrayerTimes: [PrayerTime]! @hasMany(indexName: "byUpdatedByUser", fields: ["id"])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
}

# ------------------------------------------------------------------------------------- CUSTOM TYPES

type Day {
  type: DayType!
  operatingHours: [OperatingHours!]!
}

type Hours {
  monday: Day
  tuesday: Day
  wednesday: Day
  thursday: Day
  friday: Day
  saturday: Day
  sunday: Day
}

type OperatingHours {
  open: AWSTime!
  close: AWSTime!
}

type FardPrayer {
  athan: AWSTime!
  iqamah: AWSTime!
}

type SunnahPrayer {
  start: AWSTime!
  end: AWSTime
}

type SocialMedia {
  facebook: String
  instagram: String
  twitter: String
  youtube: String
}

# ------------------------------------------------------------------------------------- ENUMS

enum AnnouncementType {
  AUDIO
  POLL
  TEXT
}

enum DayType {
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
  SUNDAY
}

enum FundraisingCampaignType {
  BILL
  COMMUNITY
  EDUCATION
  EMERGENCY_RELIEF
  ENVIRONMENT
  FUNERAL
  HEALTH
  MOSQUE
  ORPHANS
  OTHER
  REFUGEES
}

enum MemberRole {
  ADMIN
  MEMBER
}

enum UserStatus {
  ACTIVE
  BLOCKED
  DEACTIVATED
}

enum UserType {
  ADMIN
  SUPER_ADMIN
  USER
  USER_READ_ONLY
}
